# Site settings
title: Youngmmmoon's Thought.toString()
email: youngmmmoon@gmail.com
description: "Hello, I am youngmmmon"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: youngmmmoon
github_username:  young-utf

# Build settings
markdown: kramdown
permalink: pretty
